### ISSUE TITLE
Feature request: support for links in org mode

### ISSUE THREAD

**Issue by tbdcit** [Ziqi-Yang/peek#2]
It would be excellent if your package could also be used to preview links in org mode files. 

Any plans to support this?

**Comment by Ziqi-Yang** [comment]
Though I don't see this feature is practical for links for website/file, it would be nice to peek images in org mode. It is interesting. After some shallow observation, I think `org-open-at-point` can be easily integrated into Peek using `peek-definition-func`.   
It's sure that this feature will be implemented.  Thank you for your advice! <3

---

I'm now considering whether to put additional features into a new repo called `peek-collection` or not. We'll see.

**Comment by tbdcit** [comment]
Excellent, thanks for your response. 

I think that for people who use org-roam there is often a desire to see a quick preview of linked org-file (a quick google will show that there is interest in this but no real solution).

**Comment by Ziqi-Yang** [comment]
I have put additional integrations into this [repo: peek-collection](https://git.sr.ht/~meow_king/peek-collection). It's a bit tricky to enabling image inside peek view. Currently peek view stores content into a list of line strings by dividing the given content string by "\n". However, the string presentation of inline image in Emacs also contains "\n" character, which messes the true content and the image preview. I think this problem can be solved soon but recently I have a 22 days trip so I have to put it later. 

If you'd like to try, here is the in-complete version of the function for peeking link in org mode:
```emacs-lisp
(defun peek-collection-org-link ()
  "Peek the destination of link in org file.
Currently support link type(not the link prefix):
  - all internal links
  - file (without search option)
implementation reference: `org-link-open'
link format reference: https://orgmode.org/manual/Hyperlinks.html"
  (interactive)
  (when-let ((support-link-types
              '("coderef" "custom-id" "fuzzy" "radio"  ; internal link types
                ;; some of external link types
                "file"))
             (context (org-element-context))
             (object-type (org-element-type context))
             ((eq object-type 'link))
             (link-type (org-element-property :type context))
             (open-link-func
              (lambda ()
                ;; make sure open 'file' type link is in the same window
                (let ((org-link-frame-setup '((file . find-file)))
                      (line-height (pixel-line-height)))
                  (org-open-at-point)
                  ;; resize image file FIXME: peek doesn't support preview image yet
                  (when-let (((and (equal link-type "file") (image-at-point-p)))
                             (image-height (cdr (image-size (image--get-image) t)))
                             (scale (/ (float line-height) image-height)))
                    (image-transform-set-scale scale)
                    (image-toggle-display))))))
    (unless (member link-type support-link-types)
      (error (format "link with type '%s' is not supported" link-type)))
    (pcase link-type
      ("file"
       (when (org-element-property :search-option context)
         (error "doesn't support 'file' type link with search option"))))
    (unless global-peek-mode
      global-peek-mode)
    (peek-definition open-link-func)))
```

**Comment by Ziqi-Yang** [comment]
`peek-collection-org-link` function in [peek-collection](https://git.sr.ht/~meow_king/peek-collection)
